### ISSUE TITLE
Crash/freeze on Affinity Designer exporting PNGs, but export succeeds

### ISSUE THREAD

**Issue by lf-** [lf-/affinity-crimes#3]
If you export an Affinity Designer file to PNG, the application gets stuck or crashes (unsure which at this point).

**Comment by lf-** [comment]
https://codeberg.org/wanesty/affinity-wine-docs/issues/10

**Comment by wanesty** [comment]
someone found a fix!
https://codeberg.org/wanesty/affinity-wine-docs/issues/13

:p
